### ISSUE TITLE
A bit weird depth in 2.5D view

### ISSUE THREAD

**Issue by choyingw** [duxiaodan/intrinsic-lora#4]
![Screenshot from 2024-02-19 15-17-18](https://github.com/duxiaodan/intrinsic-lora/assets/43560997/8b07b933-84dc-4011-98d3-a0bc644d28e5)

Hi, 

Thank you for the good work! I wonder whether you have visualized depth in a 3D point cloud view to check if the relative depth makes sense. Somehow, I-LoRA has too many details in the depth map that indicate larger and jumpy depth. For example, in the second and fourth rows the foreground regions sometimes show colors as dark as the background, and ZoeDepth's results make more sense.

**Comment by duxiaodan** [comment]
Hi,

Thank you for your interest in our work. These results are generated by AugUNet, which gives sharper results but quantitatiely worse than the output of single step UNet models. Your observation is valid. Sometimes AugUNet does made more mistakes than ZoeDepth and our single step models. On the other hand, these images are synthetic images. Therefore some of them are not entirely geometrically feasible. For example, ZoeDepth and I-LoRA have very different predictions for the third row. It's hard to say which is more accurate due to the geometric ambiguity. The key of the paper is not to surpass existing SOTA works, but to provide a universal methods to determine what do generative models know about different intrinsics.

I hope this answers your questions.

Xiaodan

**Comment by duxiaodan** [comment]
Closing for now because of inactivity. Feel free to reopen if have further questions
